title: 착한유령의 창고
description: 각종 프로그래밍을 위한 소소한 팁을 정리하고 있습니다.
author: good-ghost (woomg dot nate dot com)
owner_url: https://good-ghost.duckdns.org/

theme: null

debug:
  compress: true
  dist: false
  shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

last-modified-at:
  date-format: '%Y/%m/%d'

exclude:
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - jekyll-rtd-theme.gemspec
